import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import Header from "@/_components/common/header/Header";
import Footer from "@/_components/common/footer/Footer";

const redHat = Red_Hat_Text({
  subsets: ["latin"],
  variable: "--font-redhat",
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ redHat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><Header/>{children}<Footer/></body>
    </html>
  );
}
